# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e9662d98dee8faf7a61b3a7044ce16cf3c95e3a5d65fe5fea65bcbb0e2768a50a79b18d1b8a79bec64f1791fad8ffc0b567122a735afe7f7e78ed7c2e3341e

test:
  secret_key_base: 2d88d74ba2930324cafb5cd234fd377231fbf3bea5206fa673c033ee5121248feec7c17055afa8af865cca11071f3c5c960838903872bf044365a83a380e582a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
